### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/tenso#98]
```
Mar 21 21:53:03 or1010051030229 microsite[15428]: (node:15428) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at ServerResponse.end (_http_outgoing.js:747:13)
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at ServerResponse.res.send (/opt/api/node_modules/woodland/lib/woodland.js:94:9)
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at Woodland.error [as onerror] (/opt/api/node_modules/tenso/lib/tenso.js:161:14)
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at Promise.then.catch.err (/opt/api/node_modules/woodland/lib/woodland.js:353:9)
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at <anonymous>
Mar 21 21:53:03 or1010051030229 microsite[15428]:     at process._tickCallback (internal/process/next_tick.js:118:7)
Mar 21 21:53:03 or1010051030229 microsite[15428]: (node:15428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 240)
```

**Comment by avoidwork** [comment]
Error is handled, but what was it passing? Likely a separate bug.

**Comment by avoidwork** [comment]
Fixed with recent changes to woodland.

**Comment by avoidwork** [comment]
Likely an object was passed to the underlying `.write()` of the socket.
